# http://localhost:8081/api/swagger-ui.html

server.port=8081
server.servlet.context-path=/api
server.servlet.path=/*

#CorsRegistry
project.cors.url = "/api/**"

spring.application.name=pedido
spring.jmx.default-domain: ${spring.application.name}

# data source
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:pedido-service
spring.datasource.username=sa
spring.datasource.password=

# jpa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
